// TrendingMovies.data.ts
import { Movie } from "@/types/movies";

export const trendingMovies: Movie[] = [
  {
    id_pelicula: 12,
    titulo: "Destino Final 5",
    sinopsis: "Sam Lawton viaja con compañeros a una convención cuando, antes de cruzar un puente colgante, tiene una premonición: el puente se rompe y todos mueren. Ordena detener el transporte y salva numerosas vidas. Pero pronto descubre que la Muerte sigue un patrón inquebrantable: cuerpos que caen desde alturas inesperadas, ductos de agua que se averían y cables eléctricos que se enredan para cobrarse venganza. Para detener la cadena de muertes, Sam deberá confiar en revelaciones ocultas en fotografías y enfrentarse a la realidad de que no puede burlar al destino sin pagar un precio definitivo.",
    duracion: 92,
    fecha_lanzamiento: "2011-08-12",
    id_productora: 4,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/destino_final_5.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/destino_final_5.mp4",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: 4,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 13,
    titulo: "Dragon Ball Z: La resurrección de Freezer",
    sinopsis: "Años después de la derrota de Freezer, sus seguidores Sorbet y Tagoma llegan a la Tierra para reunir las Esferas del Dragón y revivir a su líder. Cuando Freezer renace, busca venganza contra Goku y Vegeta con tecnologías alienígenas avanzadas que amenazan la paz del universo. Con nuevas transformaciones —Golden Freezer y Super Saiyajin Blue— la batalla escala en un combate épico que mezcla explosiones planetarias, artes marciales de otro mundo y sacrificios de los Guerreros Z. En medio de gritos de poder y ráfagas de energía, la lucha definirá el destino de la Tierra y más allá.",
    duracion: 93,
    fecha_lanzamiento: "2015-04-18",
    id_productora: 5,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/dragon_ball_z_la_resurreccion_de_freezer.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/dragon_ball_z_la_resurreccion_de_freezer.mp4",
    id_clasificacion: 2,
    calificacion_promedio: 0,
    ranking: 2,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 25,
    titulo: "Five Nights at Freddy's",
    sinopsis: "Mike Schmidt acepta trabajo como guardia nocturno en “Freddy Fazbear's Pizza”, un restaurante infantil con animatrónicos que cobran vida tras el cierre. Durante cinco noches aterradoras, Mike vigila las cámaras de seguridad y las puertas electrónicas, consciente de que los robots—un oso, un conejo, un zorro y un pato—se alimentan de niños entre las 12 a. m. y las 6 a. m. Con ruidos inquietantes y movimientos impredecibles, la tensión aumenta cada hora: luces que fallan, pasos en los pasillos y risas distorsionadas. El miedo se intensifica cuando descubre un oscuro legado de desapariciones infantiles y secretos siniestros ocultos detrás de la música infantil.",
    duracion: 92,
    fecha_lanzamiento: "2023-10-27",
    id_productora: 12,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/five_nights_at_freddys.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/five_nights_at_freddys.mp4",
    id_clasificacion: 4,
    calificacion_promedio: 0,
    ranking: 5,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 43,
    titulo: "Shrek",
    sinopsis: "Shrek, un ogro cascarrabias, vive feliz en su pantano hasta que Lord Farquaad exilia a todas las criaturas de cuentos de hadas. Para recuperar su hogar, Shrek hace un trato con Farquaad: rescatar a la princesa Fiona de un dragón y llevársela para que Farquaad la proclame reina. Acompañado del parlanchín Burro, se enfrenta a peligros y descubre que Fiona guarda un secreto que lo cambia todo: al caer la noche, se convierte en ogresa. Con humor irreverente y referencias a mitos clásicos, la película revela que el verdadero valor radica en la autenticidad y el amor más allá de las apariencias.",
    duracion: 90,
    fecha_lanzamiento: "2001-01-01",
    id_productora: 19,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/shrek_1.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/shrek_1.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: 6,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 47,
    titulo: "Terminator 3: La rebelión de las máquinas",
    sinopsis: "Diez años después de “Terminator 2”, John Connor vive en las sombras para evitar a Skynet. Pero el sistema ha enviado al Terminator TX, un modelo casi indestructible, para eliminarlo. A la vez, se envía a Kate Brewster, futura esposa de John y jefa militar en ciernes, un T-850 reprogramado para protegerlo. Al descubrir que Skynet será consciente en cuestión de horas y lanzará el Apocalipsis nuclear, John y Kate huyen mientras el T-850 frena al TX. Con explosiones en autopistas, persecuciones eléctricas y un reloj que marca el destino de la humanidad, la película muestra la lucha desesperada por retrasar el Juicio Final.",
    duracion: 109,
    fecha_lanzamiento: "2003-07-02",
    id_productora: 18,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/terminator_3_la_rebelion_de_las_maquinas.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/terminator_3_la_rebelion_de_las_maquinas.mp4",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: 7,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 51,
    titulo: "Lilo y Stitch",
    sinopsis: "Lilo, convertida en adolescente, lidia con la secundaria mientras Stitch regresa para protegerla de una amenaza intergaláctica. Con animación y acción real combinadas, redescubren el valor de la “ohana” en una aventura emotiva.",
    duracion: 108,
    fecha_lanzamiento: "2025-05-22",
    id_productora: 23,
    tipo_contenido: "cine",
    imagen_portada: "https://novacode-peliculas-cartelera.b-cdn.net/lilo_y_stitch.webp",
    url_video: "",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: 8,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 55,
    titulo: "Cómo Entrenar a tu Dragón",
    sinopsis: "Hiccup, convertido en adulto, debe enseñar a una nueva generación de vikingos a coexistir con dragones. Cuando un antiguo enemigo emerge, Hiccup y Toothless lideran una alianza para salvar su hogar. Dirigida por Dean DeBlois, mezcla acción épica con emotivos vínculos familiares.",
    duracion: 125,
    fecha_lanzamiento: "2025-06-12",
    id_productora: 26,
    tipo_contenido: "cine",
    imagen_portada: "https://novacode-peliculas-cartelera.b-cdn.net/como_entrenar_a_tu_dragon.jpg",
    url_video: "",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: 9,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 57,
    titulo: "F1: La Película",
    sinopsis: "Documental que recorre la historia de la Fórmula 1, desde sus orígenes hasta la era moderna, con imágenes inéditas de los coches más icónicos y entrevistas a leyendas del automovilismo. Dirigido por Peter Webber, ofrece una mirada inmersiva al deporte motor más prestigioso del mundo.",
    duracion: 150,
    fecha_lanzamiento: "2025-06-26",
    id_productora: 28,
    tipo_contenido: "cine",
    imagen_portada: "https://novacode-peliculas-cartelera.b-cdn.net/f1_la_pelicula.jpg",
    url_video: "",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: 10,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 58,
    titulo: "Jurassic World: El Renacer",
    sinopsis: "Tras años de paz entre humanos y dinosaurios, una nueva isla se ve amenazada por el resurgir de una variante genética desconocida. Claire y Owen regresan para investigar una serie de desapariciones que podrían desencadenar un conflicto global. Dirigida por Colin Trevorrow, fusiona acción, ciencia ficción y nostalgia jurásica.",
    duracion: 134,
    fecha_lanzamiento: "2025-07-02",
    id_productora: 28,
    tipo_contenido: "cine",
    imagen_portada: "https://novacode-peliculas-cartelera.b-cdn.net/jurassic_world_el_renacer.jpg",
    url_video: "",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: 3,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 59,
    titulo: "Superman",
    sinopsis: "Cuando un antiguo mal resurge en Metrópolis, Clark Kent debe reconciliar su legado kryptoniano con su vida humana. Con la ayuda de Lois Lane y su primo, descubrirá que el verdadero poder radica en la esperanza. Dirigida por James Gunn, reinventa al Hombre de Acero para una nueva era.",
    duracion: 140,
    fecha_lanzamiento: "2025-07-10",
    id_productora: 29,
    tipo_contenido: "cine",
    imagen_portada: "https://novacode-peliculas-cartelera.b-cdn.net/superman.jpg",
    url_video: "",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: 1,
    age: "0",
    genres: [],
  }

];