import { Movie } from "@/types/movies";

export const dataMovies: Movie[] = [
  {
    id_pelicula: 1,
    titulo: "Amargo Mar",
    sinopsis: "Una perspectiva boliviana sobre la Guerra del Pacífico (1879). A través de personajes que representan distintos estratos sociales, la película denuncia la responsabilidad de autoridades y ciudadanos en la pérdida del litoral. Con escenas dramáticas en los campos de batalla y recuerdos de familias separadas, revela cómo el orgullo nacional chocó contra decisiones fatídicas, marcando para siempre la memoria colectiva de Bolivia.",
    duracion: 100,
    fecha_lanzamiento: "1984-01-01",
    id_productora: 1,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/amargo_mar.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/amargo_mar.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 2,
    titulo: "Boquerón",
    sinopsis: "En septiembre de 1932, cuatro jóvenes bolivianos de diferentes regiones y clases sociales se alistan para defender el fuerte de Boquerón contra las tropas paraguayas durante la Guerra del Chaco. Con camaradería y sacrificio, enfrentan el hambre, el calor y la falta de armamento. Entre historias de amistad, traición y esperanza, la película retrata el heroísmo cotidiano y los conflictos internos de quienes lucharon por un territorio y vieron cómo sus sueños juveniles se desvanecían en las trincheras.",
    duracion: 124,
    fecha_lanzamiento: "2015-01-01",
    id_productora: 2,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/boqueron.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/boquerón.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 3,
    titulo: "Cementerio de elefantes",
    sinopsis: "Juvenal, un hombre de 33 años y alcohólico desde los 14, decide internarse voluntariamente en el Cementerio de los ElefantesS, un refugio en La Paz donde los bebedores van a morir. Allí revive su infancia, la desaparición de su madre y el abandono familiar, mientras bebe sin tregua. En su descenso hacia el olvido, narra recuerdos de calles empedradas, mercados atestados y la solidaridad de amigos caídos. Con un tono melancólico y escenas que alternan la lucidez y la alucinación, muestra el precio de la soledad humana.",
    duracion: 90,
    fecha_lanzamiento: "2008-01-01",
    id_productora: 3,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/cementerio_de_elefantes.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/cementerio_de_elefantes.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 4,
    titulo: "Chaco",
    sinopsis: "En 1934, durante la Guerra del Chaco, un regimiento indígena boliviano compuesto por aymaras y quechuas, liderado por el general alemán Hans Kundt, atraviesa el implacable desierto. Con escasez de agua, enfermedades y órdenes contradictorias, los soldados deben sobrevivir a emboscadas y al calor abrasador. A través de las voces de los guerreros, la película expone las tensiones culturales y la brutalidad del conflicto, mostrando cómo la resistencia de un pueblo marginado desafía el poder militar en un terreno tan implacable como la historia misma.",
    duracion: 80,
    fecha_lanzamiento: "2020-01-01",
    id_productora: null,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/chaco.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/chaco.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 5,
    titulo: "Con las alas rotas",
    sinopsis: "Un triángulo amoroso en un entorno urbano: Mirka, una joven frágil, se ve atrapada entre Boris, un delincuente rebelde, y Marcelo, un abogado respetable. Mientras la ciudad de La Paz se levanta en caos diario, Mirka debe elegir entre la pasión peligrosa y la seguridad ilusoria. Con escenas nocturnas en callejones, balaceras interrumpidas y diálogos llenos de tensión, la película explora cómo las decisiones impulsivas pueden romper o sostener los vínculos familiares y personales.",
    duracion: 80,
    fecha_lanzamiento: "1938-06-15",
    id_productora: 16,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/con_las_alas_rotas.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/con_las_alas_rotas.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 6,
    titulo: "Con las alas rotas 2",
    sinopsis: "Secuela que retoma la historia de la niña “Princesa”, abandonada en un basurero y rescatada por alcohólicos e inhaladores en las calles de El Alto. Años después, la niña crece en un albergue. La cinta explora la corrupción policial, el tráfico de drogas y las pandillas juveniles que reclutan a menores de edad. Con escenas crudas en callejones, testimonios de madres solteras y rituales de coca, la película muestra el ciclo de violencia y destrucción de la inocencia, mientras la “Princesa” lucha por hallar su lugar en un mundo hostil.",
    duracion: 90,
    fecha_lanzamiento: "2015-10-21",
    id_productora: 16,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/con_las_alas_rotas_2.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/con_las_alas_rotas_2.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 7,
    titulo: "Con las alas rotas 3",
    sinopsis: "Tercera parte que cierra la trilogía: la “Princesa” y otros niños de la calle enfrentan la adolescencia. Mientras intentan sobrevivir, se organizan en pequeños grupos para robar y mendigar. La cinta expone la marginalidad y las luchas internas: disputas por el control de territorios callejeros, la influencia de los mayores de edad y la búsqueda de afecto. Con imágenes en mercados improvisados y fogatas de cartones, se revela el costo emocional y físico de crecer sin familia, y cómo la esperanza se convierte en resistencia.",
    duracion: 90,
    fecha_lanzamiento: "2017-09-15",
    id_productora: 16,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/con_las_alas_rotas_3.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/con_las_alas_rotas_3.mp4",
    id_clasificacion: 1,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 8,
    titulo: "Destino Final",
    sinopsis: "Alex Browning, un estudiante de secundaria, tiene una aterradora premonición justo antes de despegar en un vuelo con sus compañeros. Ve cómo el avión explota en llamas, matando a todos a bordo. En pánico, convence a varios amigos para abandonar el avión. Minutos después, el desastre ocurre tal como lo vio. Creyendo haber engañado al destino, comienzan a experimentar muertes macabras: desde una tubería de escape que explota hasta postes de señales que se desploman. Alex descubre un viejo profesor que sobrevivió a un accidente similar décadas atrás y debe descifrar el patrón de la Muerte antes de que continúe su racha homicida.",
    duracion: 98,
    fecha_lanzamiento: "2000-03-17",
    id_productora: 4,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/destino_final_1.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/destino_final_1.mp4",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 9,
    titulo: "Destino Final 2",
    sinopsis: "Un año después de los eventos del Vuelo 180, Kimberly Corman viaja con varios amigos a Daytona Beach. En la autopista, tiene una vívida premonición: un camión volcará y provocará un accidente masivo. Detiene su auto justo antes del desastre y salva a varios automovilistas, incluyendo a la oficial Burke. Cuando el accidente ocurre, la Muerte empieza a cobrarse vidas en secuencia: una severa caída de un poste de luz, un tejado que se derrumba y autos que arden en llamas. Kimberly y Burke unen fuerzas para entender la mecánica de la Muerte y tratar de romper el ciclo antes de que sea demasiado tarde.",
    duracion: 90,
    fecha_lanzamiento: "2003-01-31",
    id_productora: 4,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/destino_final_2.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/destino_final_2.mp4",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
  {
    id_pelicula: 10,
    titulo: "Destino Final 3",
    sinopsis: "Wendy Christensen, estudiante de secundaria, asiste con sus amigos al parque de atracciones en su noche de graduación. Al subirse a la montaña rusa, Wendy ve en una visión cómo la atracción choca y destruye a todos los pasajeros. Logra liberar a varios antes del desastre, pero la muerte encuentra formas retorcidas de alcanzarlos: desde cables que se enredan en maquinaria hasta explosiones de gas en la cafetería. Mientras investiga viejas fotografías, Wendy descubre mensajes ocultos que le señalan quién será el siguiente. En una carrera contrarreloj, lucha por descifrar el patrón de la muerte y salvar a los pocos sobrevivientes restantes.",
    duracion: 93,
    fecha_lanzamiento: "2006-02-10",
    id_productora: 4,
    tipo_contenido: "streaming",
    imagen_portada: "https://novacode-portadas.b-cdn.net/destino_final_3.jpg",
    url_video: "https://peliculas-nova.b-cdn.net/destino_final_3.mp4",
    id_clasificacion: 3,
    calificacion_promedio: 0,
    ranking: null,
    age: "0",
    genres: [],
  },
]